version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - java -version
      - yum -y install java-11
      - update-alternatives --auto javac
      - update-alternatives --auto java
      - java -version
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/user-service.jar
  discard-paths: yes